export const MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING';
export const MONGO_DB_NAME = 'MONGO_DB_NAME';
export const MONGO_COLLECTION_NAME = 'MONGO_COLLECTION_NAME';
export const JWT_SECRET_KEY = 'JWT_SECRET_KEY';
export const JWT_REFRESH_SECRET_KEY='JWT_REFRESH_SECRET_KEY';
export const PORT = 'PORT';
