export const MONGO_CONNECTION_STRING = 'MONGO_CONNECTION_STRING';
export const MONGO_DB_NAME = 'MONGO_DB_NAME';
export const MONGO_COLLECTION_NAME = 'MONGO_COLLECTION_NAME';

export const PORT = 'PORT';
